### ISSUE TITLE
icon color notification on dark statusbar

### ISSUE THREAD

**Issue by akbarnash** [jeancsanchez/JCPlayer#106]
![Screenshot_20200611-101354](https://user-images.githubusercontent.com/45724295/84341123-92099100-abcc-11ea-9c32-01f846b27e0e.jpg)

can i change the color of button notification so it can be visible on dark statusbar?

**Comment by jeancsanchez** [comment]
Probably fixed in version 1.7.0

**Comment by KomalJagtap128** [comment]
Hello @jeancsanchez I m  using JCPlayer lib , I am trying to hide the next and previous button of notification , but not able to  hide next and previous button.Please help me

**Comment by LunevNF** [comment]
Not fixed:
implementation 'com.github.jeancsanchez:JcPlayer:2.7.0'
